manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cannonkeys
      url-base: https://github.com/cannonkeys
  projects:
    - name: zmk
      remote: cannonkeys
      revision: main  # This points to CannonKeys' version of ZMK
      import: app/west.yml
    - name: zmk-cannonkeys-keyboards
      remote: cannonkeys
      revision: main
  self:
    path: config